Algoritmo "Aula 8"

Var
n1,n2,media: real


Inicio

escreval("Digite a primeira nota do aluno:")
leia(n1)

escreval("Digite a segunda nota do aluno:")
leia(n2)

media <- (n1+n2)/2

se media >= 7 entao

escreval("O Aluno foi aprovado!")

senao

se (media >=5 ) e (media <7) entao

escreval("O Aluno está me recuperação")

senao

se media < 4.99 entao

escreval ("O Aluno está reprovado!")

fimse
fimse
fimse

Fimalgoritmo