Algoritmo "contar de 0 ate onde o usuario quiser"

Var
valor,salto,contador: Inteiro



Inicio
     contador <- 0
     escreva("Quer contar até quanto? ")
     leia(valor)
     escreva("Qual será o valor do salto? ")
     leia(salto)
     enquanto (contador <= valor) faca
       escreval(contador)
       contador <- contador + salto
     FimEnquanto
     Escreval("Terminei de contar")
     


Fimalgoritmo