Algoritmo "CONTAR DE 1 ATE 10. 10 ATE 1"

Var
Cont,Cont2: inteiro
R: caractere


Inicio

Cont <- 1
Cont2 <- 10

Escreval(" [1] De 1 a 10 ")
Escreval(" [2] De 10 a 1 ")
Escreval(" [3] Sair")
leia(R)
limpatela

Se R = "1" entao

Repita

escreval(cont)

cont <- cont + 1

Ate (Cont > 10)

senao

se R = "2" entao

Repita

escreval (Cont2)

cont2 <- cont2 - 1

Ate (Cont2 < 1)

senao

se R = "3" entao

escreval("Saindo...")

fimse
fimse
fimse

Fimalgoritmo