Algoritmo "EX66"
//66) Escreva um programa que leia um número qualquer e mostre a
//tabuada desse número, usando a estrutura para. Ex: Digite um valor: 5
//5 x 1 = 5
//5 x 2 = 10
//5 x 3 = 15 ...
Var

N,V,C: inteiro


Inicio
      escreval("Qual tabuada deseja imprimir ?")
      leia(V)
      


      Para N de 1 ate 10 faca

      c <- v * n
      
      escreval(N," x",V," = ",C)

      
      fimpara

Fimalgoritmo