Algoritmo "EX67"
//Faça um programa usando a estrutura “para” que leia um número inteiro
//positivo e mostre na tela uma contagem de 0 até o valor digitado:
//Ex: Digite um valor: 9
//Contagem: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, FIM!
Var
V,C: inteiro


Inicio
      escreval("Digite até que valor deseja contar: ")
      leia(v)

      para C de 0 ate V faca
      escreva("..",C)
      fimpara
      escreva(".. Fim")

Fimalgoritmo