Algoritmo "EX73"
//Crie um programa que preencha automaticamente (usando lógica,
//não apenas atribuindo diretamente) um vetor numérico com 10 posições
//9,8,7,6,5,4,3,2,1
Var

N: vetor[1..10] de inteiro
i: inteiro
soma: inteiro
Inicio

      soma <- 9
      
      Para i <- 1 ate 10 faca
           n[i] <- soma
           soma <- soma - 1
           escreval(n[i])
      FimPara
      



Fimalgoritmo