Algoritmo "EX74"
//Crie um programa que preencha automaticamente (usando lógica,
//não apenas atribuindo diretamente) um vetor numérico com 10 posições
//5,3,5,3,5,3,5,3,5,3
Var

N: vetor[1..10] de inteiro
i: inteiro

Inicio


      
      Para i <- 1 ate 5 faca
      
           n[i] <- 5
           escreval(n[i])
           n[i] <- n[i] - 2
           escreval (n[i])
           n[i] <- n[i] + 2
           
      FimPara
      



Fimalgoritmo