Algoritmo "EX90"
//Desenvolva um algoritmo que leia dois valores pelo teclado e passe
//esses valores para um procedimento Somador() que vai calcular e
//mostrar a soma entre eles.

var

A,B: inteiro
soma: real


Procedimento Calculo()
inicio
soma <- (a+b)
escreval("A soma destes números é: ",soma)
FimProcedimento

Inicio

      Escreval("Digite um valor: ")
      leia(A)
      
      Escreval("Digite outro valor: ")
      leia(B)
      
      limpatela
      Calculo()

Fimalgoritmo